apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dshub
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://git.duzon.com/ynlee0804/mlops-dashboard.git
    targetRevision: master
    path: deploy/dshub
  destination:
    server: https://kubernetes.default.svc
    namespace: dshub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
