apiVersion: v1
kind: PersistentVolume
metadata:
  name: ds-nfs-dshub
spec:
  capacity:
    storage: 600Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: bigdata-nas-3.wehago.com
    path: /ifs/data/nfs/DS
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ds-nfs
  namespace: dshub
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: ds-nfs-dshub
  resources:
    requests:
      storage: 600Ti
