apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-sllm-nfs
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: bigdata-nas-3.wehago.com
    path: /ifs/data/nfs/dev/sllm
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-sllm
  namespace: datascience-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: shared-sllm-nfs
  resources:
    requests:
      storage: 10Ti
